-- MySQL Script generated by MySQL Workbench
-- 12/01/14 17:33:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bagawaredb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bagawaredb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bagawaredb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bagawaredb` ;

-- -----------------------------------------------------
-- Table `bagawaredb`.`LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bagawaredb`.`LOCATION` (
  `locationcode` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`locationcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagawaredb`.`TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bagawaredb`.`TYPE` (
  `typecode` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`typecode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagawaredb`.`ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bagawaredb`.`ACCOUNT` (
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `fname` VARCHAR(25) NOT NULL,
  `lname` VARCHAR(25) NOT NULL,
  `birthday` DATE NOT NULL,
  `accountcreatedate` DATE NOT NULL,
  `LOCATION_locationcode` VARCHAR(25) NOT NULL,
  `TYPE_typecode` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`username`, `LOCATION_locationcode`, `TYPE_typecode`),
  INDEX `fk_ACCOUNT_LOCATION_idx` (`LOCATION_locationcode` ASC),
  INDEX `fk_ACCOUNT_TYPE1_idx` (`TYPE_typecode` ASC),
  CONSTRAINT `fk_ACCOUNT_LOCATION`
    FOREIGN KEY (`LOCATION_locationcode`)
    REFERENCES `bagawaredb`.`LOCATION` (`locationcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACCOUNT_TYPE1`
    FOREIGN KEY (`TYPE_typecode`)
    REFERENCES `bagawaredb`.`TYPE` (`typecode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagawaredb`.`LOST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bagawaredb`.`LOST` (
  `clientid` VARCHAR(9) NOT NULL,
  `fnameclient` VARCHAR(25) NOT NULL,
  `lnameclient` VARCHAR(25) NOT NULL,
  `telnumber` VARCHAR(9) NOT NULL,
  `email` VARCHAR(25) NULL,
  `idscan` BLOB NOT NULL,
  `baglabelcode` VARCHAR(25) NULL,
  `brand` VARCHAR(25) NULL,
  `color` VARCHAR(25) NULL,
  `weight` FLOAT NULL,
  `description` VARCHAR(250) NULL,
  `LOCATION_locationcode` VARCHAR(25) NOT NULL,
  `Datecreated` DATE NULL,
  `Status` VARCHAR(12) NULL,
  PRIMARY KEY (`clientid`, `LOCATION_locationcode`),
  INDEX `fk_LOST_LOCATION1_idx` (`LOCATION_locationcode` ASC),
  CONSTRAINT `fk_LOST_LOCATION1`
    FOREIGN KEY (`LOCATION_locationcode`)
    REFERENCES `bagawaredb`.`LOCATION` (`locationcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagawaredb`.`FOUND`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bagawaredb`.`FOUND` (
  `baglabelcode` VARCHAR(25) NOT NULL,
  `brand` VARCHAR(25) NOT NULL,
  `color` VARCHAR(25) NOT NULL,
  `weight` FLOAT NOT NULL,
  `image` VARCHAR(50) NULL,
  `description` VARCHAR(250) NOT NULL,
  `LOCATION_locationcode` VARCHAR(25) NOT NULL,
  `Datecreated` DATE NULL,
  `Status` VARCHAR(12) NULL,
  PRIMARY KEY (`baglabelcode`, `LOCATION_locationcode`),
  INDEX `fk_FOUND_LOCATION1_idx` (`LOCATION_locationcode` ASC),
  CONSTRAINT `fk_FOUND_LOCATION1`
    FOREIGN KEY (`LOCATION_locationcode`)
    REFERENCES `bagawaredb`.`LOCATION` (`locationcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
