/*
 * worker create case popup screen V 1- A popup from where a worker can create
 * a new case, either for a lost bag or a found one
 */
package bagawareapp;

/**
 *
 * @author Team2FYS - IS106
 */
public class CasePopupNew extends javax.swing.JFrame {

    /**
     * Creates new form CasePopupNew
     */
    public CasePopupNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_found = new javax.swing.JButton();
        button_lost = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_found.setText("Found bagage");
        button_found.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_foundActionPerformed(evt);
            }
        });

        button_lost.setText("Client");
        button_lost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lostActionPerformed(evt);
            }
        });

        jLabel1.setText("Select the case type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(button_found, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(button_lost, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_found)
                    .addComponent(button_lost))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_foundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_foundActionPerformed
       //close choice menu
        this.dispose();
        //open create new case window
        CasePopupNewBagage CCreate = new CasePopupNewBagage();
                        CCreate.setVisible(true);
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            // these lines force the screen to the foreground and centere it
                            public void run() {
                                CCreate.toFront();
                                CCreate.repaint();
                                CCreate.setLocationRelativeTo(null);
                            }
                        });
                        
                        
    }//GEN-LAST:event_button_foundActionPerformed

    private void button_lostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lostActionPerformed
        //close choice menu
        this.dispose();
        //open create new case window
        CasePopupNewClient CCreate = new CasePopupNewClient();
                        CCreate.setVisible(true);
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            // these lines force the screen to the foreground and centere it
                            public void run() {
                                CCreate.toFront();
                                CCreate.repaint();
                                CCreate.setLocationRelativeTo(null);
                            }
                        });
       
    }//GEN-LAST:event_button_lostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasePopupNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasePopupNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasePopupNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasePopupNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasePopupNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_found;
    private javax.swing.JButton button_lost;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
